"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = '$all'

[status]
format = "$status $symbol"
success_symbol = "✔"
symbol = "✘"
disabled = false

[line_break]
disabled = true

[character]
success_symbol = '#'
